In [6]:
import heapq
from collections import defaultdict

import matplotlib.pylab as plt
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

## 데이터 로드

In [19]:
import pandas as pd

fp_df = pd.read_csv('Faceplate.csv')
fp_df.set_index('Transaction', inplace=True)
print(fp_df.shape)
print(fp_df)

(10, 6)
             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0
6              0      1     1       0      0       0
7              1      0     1       0      0       0
8              1      1     1       0      1       0
9              1      1     1       0      0       0
10             0      0     0       0      0       1

In [20]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# create frequent itemsets
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)

# and convert into rules
rules = association_rules(itemsets, metric='confidence', min_threshold=0.5)
rules.sort_values(by=['lift'], ascending=False).head(6)

print(rules.sort_values(by=['lift'], ascending=False)
      .drop(columns=['antecedent support', 'consequent support', 'conviction', 'leverage', 'zhangs_metric'])
      .head(6))

       antecedents   consequents  support  confidence      lift
13    (White, Red)       (Green)      0.2         0.5  2.500000
15         (Green)  (White, Red)      0.2         1.0  2.500000
4          (Green)         (Red)      0.2         1.0  1.666667
12  (White, Green)         (Red)      0.2         1.0  1.666667
7         (Orange)       (White)      0.2         1.0  1.428571
8          (Green)       (White)      0.2         1.0  1.428571

C:\Users\bywor\anaconda3\envs\2023-DS-A\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

## 랜덤

In [21]:
# Prepare the dataset for table 14.6 based on table 14.5
from itertools import chain
randomTransactions = [{8}, {3,4,8}, {8}, {3,9}, {9}, {1,8}, {6,9}, {3,5,7,9}, {8}, set(), 
                      {1,7,9}, {1,4,5,8,9}, {5,7,9}, {6,7,8}, {3,7,9}, {1,4,9}, {6,7,8}, {8}, set(), {9},
                      {2,5,6,8}, {4,6,9}, {4,9}, {8,9}, {6,8}, {1,6,8}, {5,8}, {4,8,9}, {9}, {8},
                      {1,5,8}, {3,6,9}, {7,9}, {7,8,9}, {3,4,6,8}, {1,4,8}, {4,7,8}, {8,9}, {4,5,7,9}, {2,8,9},
                      {2,5,9}, {1,2,7,9}, {5,8}, {1,7,8}, {8}, {2,7,9}, {4,6,9}, {9}, {9}, {6,7,8}]
print(randomTransactions)
uniqueItems = sorted(set(chain.from_iterable(randomTransactions)))
randomData = pd.DataFrame(0, index=range(len(randomTransactions)), columns=uniqueItems)
for row, transaction in enumerate(randomTransactions):
    for item in transaction:
        randomData.loc[row][item] = 1
randomData.head()

[{8}, {8, 3, 4}, {8}, {9, 3}, {9}, {8, 1}, {9, 6}, {9, 3, 5, 7}, {8}, set(), {1, 9, 7}, {1, 4, 5, 8, 9}, {9, 5, 7}, {8, 6, 7}, {9, 3, 7}, {1, 4, 9}, {8, 6, 7}, {8}, set(), {9}, {8, 2, 5, 6}, {9, 4, 6}, {9, 4}, {8, 9}, {8, 6}, {8, 1, 6}, {8, 5}, {8, 9, 4}, {9}, {8}, {8, 1, 5}, {9, 3, 6}, {9, 7}, {8, 9, 7}, {8, 3, 4, 6}, {8, 1, 4}, {8, 4, 7}, {8, 9}, {9, 4, 5, 7}, {8, 9, 2}, {9, 2, 5}, {1, 2, 9, 7}, {8, 5}, {8, 1, 7}, {8}, {9, 2, 7}, {9, 4, 6}, {9}, {9}, {8, 6, 7}]

   1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  1  0
1  0  0  1  1  0  0  0  1  0
2  0  0  0  0  0  0  0  1  0
3  0  0  1  0  0  0  0  0  1
4  0  0  0  0  0  0  0  0  1

In [23]:
# create frequent itemsets
itemsets = apriori(randomData, min_support=2/len(randomData), use_colnames=True)
# and convert into rules
rules = association_rules(itemsets, metric='confidence', min_threshold=0.7)
print(rules.sort_values(by=['lift'], ascending=False)
      .drop(columns=['antecedent support', 'consequent support', 'conviction', 'leverage', 'zhangs_metric'])
      .head(6))

  antecedents consequents  support  confidence      lift
3      (8, 3)         (4)     0.04         1.0  4.545455
1      (1, 5)         (8)     0.04         1.0  1.851852
2      (2, 7)         (9)     0.04         1.0  1.851852
4      (3, 4)         (8)     0.04         1.0  1.851852
5      (3, 7)         (9)     0.04         1.0  1.851852
6      (4, 5)         (9)     0.04         1.0  1.851852

C:\Users\bywor\anaconda3\envs\2023-DS-A\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

## 책

In [27]:
all_books_df = pd.read_csv('CharlesBookClub.csv')

# create the binary incidence matrix
ignore = ['Seq#', 'ID#', 'Gender', 'M', 'R', 'F', 'FirstPurch', 'Related Purchase',
          'Mcode', 'Rcode', 'Fcode', 'Yes_Florence', 'No_Florence']
count_books = all_books_df.drop(columns=ignore)
count_books[count_books > 0] = 1

count_books.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,1,0,1,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0

In [36]:
# create frequent itemsets and rules
itemsets = apriori(count_books, min_support=200/4000, use_colnames=True)
rules = association_rules(itemsets, metric='confidence', min_threshold=0.5)

print('Number of rules', len(rules))

# Display 25 rules with highest lift
rules.sort_values(by=['lift'], ascending=False).head(25)\
     .drop(columns=['antecedent support', 'consequent support', 'conviction', 'leverage', 'zhangs_metric'])

Number of rules 81

C:\Users\bywor\anaconda3\envs\2023-DS-A\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,support,confidence,lift
64,"(RefBks, YouthBks)","(ChildBks, CookBks)",0.05525,0.680000,2.809917
73,"(RefBks, DoItYBks)","(ChildBks, CookBks)",0.06125,0.662162,2.736207
60,"(DoItYBks, YouthBks)","(ChildBks, CookBks)",0.06700,0.648910,2.681448
80,"(RefBks, GeogBks)","(ChildBks, CookBks)",0.05025,0.614679,2.539995
69,"(GeogBks, YouthBks)","(ChildBks, CookBks)",0.06325,0.605263,2.501087
77,"(DoItYBks, GeogBks)","(ChildBks, CookBks)",0.06050,0.599010,2.475248
67,"(ChildBks, GeogBks, CookBks)",(YouthBks),0.06325,0.577626,2.424452
71,"(RefBks, ChildBks, CookBks)",(DoItYBks),0.06125,0.591787,2.323013
48,"(DoItYBks, GeogBks)",(YouthBks),0.05450,0.539604,2.264864
62,"(RefBks, ChildBks, CookBks)",(YouthBks),0.05525,0.533816,2.240573
58,"(ChildBks, DoItYBks, CookBks)",(YouthBks),0.06700,0.524462,2.201309
57,"(ChildBks, YouthBks, CookBks)",(DoItYBks),0.06700,0.558333,2.191691
34,"(RefBks, ChildBks)",(DoItYBks),0.07100,0.553606,2.173135
75,"(ChildBks, GeogBks, CookBks)",(DoItYBks),0.06050,0.552511,2.168838
21,"(GeogBks, ChildBks)",(YouthBks),0.07550,0.516239,2.166797
45,"(GeogBks, CookBks)",(YouthBks),0.08025,0.513600,2.155719
63,"(RefBks, ChildBks, YouthBks)",(CookBks),0.05525,0.891129,2.144715
17,"(ChildBks, YouthBks)",(DoItYBks),0.08025,0.544068,2.135693
51,"(RefBks, CookBks)",(DoItYBks),0.07450,0.533095,2.092619
28,(RefBks),"(ChildBks, CookBks)",0.10350,0.505495,2.088820
70,"(RefBks, DoItYBks, CookBks)",(ChildBks),0.06125,0.822148,2.086669
15,(YouthBks),"(ChildBks, CookBks)",0.12000,0.503673,2.081292
72,"(RefBks, DoItYBks, ChildBks)",(CookBks),0.06125,0.862676,2.076236
23,"(ChildBks, CookBks)",(DoItYBks),0.12775,0.527893,2.072198
25,(DoItYBks),"(ChildBks, CookBks)",0.12775,0.501472,2.072198